### PR TITLE
Prepare 2.3.6 release

### PR DESCRIPTION
**Pull request by dnicolodi**

### CODE REVIEW

**Comment by dnicolodi** [comment]
Thanks @blais Can you also push a `2.3.6` tag?

**Comment by blais** [comment]
Done, and I twine uploaded sdist. (Man the new API token system on PyPi is poorly documented). PyPi won't accept by Linux wheel /shrug

**Comment by dnicolodi** [comment]
Thanks Martin. However, the CI job also uploads the sdist. The CI job build the wheels correctly but the upload failed. I don't know if it is because the API token stored in the GitHub secrets expired or because it tried to replace the sdist you uploaded, something that is non allowed.

**Comment by dnicolodi** [comment]
Funny. Some wheels where uploaded but then PyPI returned a `403 Forbidden`. I think the token store in the Github secrets may have been invalidated when you generated a new one to upload the sdist. I think the easiest is for you to download the build artifacts from here https://github.com/beancount/beancount/actions/runs/6425302997#artifacts unzip the zip and upload with twine

**Comment by dnicolodi** [comment]
Probably replacing the token in the Github secrets is a good idea for the next release

**Comment by dnicolodi** [comment]
> PyPi won't accept by Linux wheel /shrug

CI also build (and eventually uploads) Linux wheels.

**Comment by blais** [comment]
Ah yes, I had to reissue the github token. I'll update in a few hours.

**Comment by blais** [comment]
Updated.

**Comment by dnicolodi** [comment]
I don't know how to resume the upload job from CI. It would be great if you could upload manually the wheels that haven't been uploaded.

**Comment by blais** [comment]
I just reran the jobs.

**Comment by dnicolodi** [comment]
Great, thanks! Everything looks good.

**Pull request merged**
