### PR TITLE
parser: Read input data from Python file objects

### PR DESCRIPTION
**Pull request by dnicolodi**
First couple of patches extracted from the too-big-to-merge PR and incorporating first review comments.

### CODE REVIEW

**Comment by dnicolodi** [comment]
Hold on. Something is wrong with the tests...

**Comment by blais** [comment]
Some of the errors are due to differences in filename passed to the options parsing code in the grammar.

**Comment by dnicolodi** [comment]
I fixed the tests failure. All should be good now. I never remember if Github sends notifications when a PR branch is force pushed...

**Comment by dnicolodi** [comment]
@balis, sorry for messing up the indentation in the patch. I understand from the follow up patch that you prefer a coding style where braces are used also for single statements. I'll try to adhere to that in the future.

**Comment by blais** [comment]
No worries
Yes, unconditional braces, and also no spaces within parens.

**Comment by dnicolodi** [comment]
> Yes, unconditional braces, and also no spaces within parens.

I'll stick to this style. What about the space between the negation
operator and its argument: `(! foo)` or `(!foo)` ? I think there are a
mix of the two styles in the codebase now.

**Comment by blais** [comment]
No space ideally

**Pull request merged**
