### PR TITLE
Update CI job to build and upload release artifacts

### PR DESCRIPTION
**Pull request by dnicolodi**

### CODE REVIEW

**Comment by dnicolodi** [comment]
@blais Merging this and pushing a `2.3.6` release tag should be sufficient to get a release and the associated sdist and wheels uploaded on PyPI. This creates wheels for Windows x86 and x86-64, Linux x86-64 and arrm64, macOS x86-64 and arm64, for Python 3.7 to 3.12. Other architectures can be added if requested.

**Comment by dnicolodi** [comment]
There is a failing test. I'm looking into it.

**Comment by blais** [comment]
Thanks Daniele. No rush, I'll wait until you say it's ready. Appreciate the help.

**Comment by dnicolodi** [comment]
It should be good to go now.

**Comment by blais** [comment]
You're amazing! tyty

**Pull request merged**
