### PR TITLE
Optionally write a source for entry in printer.print_entries and printer.print_entry v2

### PR DESCRIPTION
**Pull request by Ev2geny**
This is a pull request to address the new feature discussed here https://github.com/beancount/beancount/issues/807
This is a re-run of the previous [pull request](https://github.com/beancount/beancount/pull/810), but now with all commits squashed, as requested.

It adds an optional `write_source` parameter to the `printer.print_entry` and `printer.print_entries` functions to be able to add source file and line number in a format interpretable as a message location for Emacs, VSCode.

This is very useful for "debugging" of beancount ledger especially in multi file setup. as it allows to immediately go to the file and line number in question by clicking on the message location.

**Examples:**

In VSCode terminal

image

In VSCode jupyter notebook

image

### CODE REVIEW

**Comment by Ev2geny** [comment]
@dnicolodi, as I understand from your comments [here ](https://github.com/beancount/beancount/pull/810#issuecomment-1983177346) your proposal is as follows:

1) Do not modify the [EntryPrinter](https://github.com/beancount/beancount/blob/a5ce3382c95d0e273aad5de1753def6256fb7a3d/beancount/parser/printer.py#L92) class

2) Do not modify the [print_entry ](https://github.com/beancount/beancount/blob/a5ce3382c95d0e273aad5de1753def6256fb7a3d/beancount/parser/printer.py#L387)function

3) Modify only the  [print_entries](https://github.com/beancount/beancount/blob/a5ce3382c95d0e273aad5de1753def6256fb7a3d/beancount/parser/printer.py#L408C5-L408C18) function

Did I understand your previous comments correctly?

**Comment by dnicolodi** [comment]
Please don't open new PRs to follow up review feedback. Just force push the modified comments to the same branch, and thus to the same PR. Opening a new PR makes following the review process unnecessarily hard.

**Comment by dnicolodi** [comment]
> Did I understand your previous comments correctly?

Not really. What I'm suggesting is for you to keep your version of `print_entries()` that adds the additional comment as you like it. I don't think the ability to add the source of the entry in a comment is a widespread enough need to warrant addition to beancount, especially if it can be implemented in a couple of lines on top of existing facilities.

**Comment by Ev2geny** [comment]
> Please don't open new PRs to follow up review feedback. Just force push the modified comments to the same branch, and thus to the same PR. Opening a new PR makes following the review process unnecessarily hard.

Sorry, you requested me to  [squash the commits into just one commit ](https://github.com/beancount/beancount/pull/810#issuecomment-1983177346)and I couldn't figure out how to do this at already submitted PR

**Comment by Ev2geny** [comment]
> > Did I understand your previous comments correctly?
> 
> Not really. What I'm suggesting is for you to keep your version of `print_entries()` that adds the additional comment as you like it. I don't think the ability to add the source of the entry in a comment is a widespread enough need to warrant addition to beancount, especially if it can be implemented in a couple of lines on top of existing facilities.

Noted and understood.

**Comment by blais** [comment]
I'm not sure what the kerfuffle is and what not. I agree the feature is a bit overkill but don't mind so much. If people have setups where this way of surfacing the source location (instead of a LSP or whatever) helps them why not. I'd prefer the condition be in the caller but otherwise seems fine to me.

**Pull request merged**
