### PR TITLE
Limit format alignment to directives and postings

### LINKED ISSUE #400: bean-format splits ledger payee
**[Original report](https://bitbucket.org/blais/beancount/issue/400) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

```
2019-07-29 * This is a 100 EUR test payment
    Expenses:Test             100.00 EUR
    Assets:Bank              -100.00 EUR
```

ends up as: 

```
bean-format -w 30 d

2019-07-29 * This is a              100 EUR test payment
    Expenses:Test                100.00 EUR
    Assets:Bank                 -100.00 EUR
```

The “100 EUR” in the payee description is parsed as an amount.

bean-format should ignore lines starting with ^\[0-9\] since that’s a transaction header in both ledger and beancount.

### PR DESCRIPTION
**Pull request by tbm**
Restrict format alignment to directives and postings, but don't
apply it to metadata.

Fixes #400

### CODE REVIEW

**Comment by tbm** [comment]
Currently, running `bean-format -w 20` on

```
2020-11-10 * Test
  payment_amount: 20.00 EUR
  Assets:Test                     10.00 EUR
  Assets:Test           -10.00 EUR
```

will result in

```
2020-11-10 * Test
  payment_amount:      20.00 EUR
  Assets:Test          10.00 EUR
  Assets:Test         -10.00 EUR
```

I don't think the metadata should be aligned (then again, I'm surprised to see that directives are aligned, so maybe some people also want metadata to be aligned).

With this patch, you get:

```
2020-11-10 * Test
  payment_amount: 20.00 EUR
  Assets:Test          10.00 EUR
  Assets:Test         -10.00 EUR
```

Let me know if you agree.  If not, close this PR and I'll pipe it through sed locally to get the output I want.

**Comment by dnicolodi** [comment]
Just to make `git log` out put a bit more self explanatory, can you please mention that this applied to `bean-format` somewhere in the commit message, better in the subject line like `bean-format: Align amounts only when appearing in directives and postings`?

**Comment by tbm** [comment]
> can you please mention that this applied to bean-format

Done!

**Comment by dnicolodi** [comment]
I still don't understand what you mean with "format alignment". Beancount grammar does not have an element called format. Looking at the example I think you mean "amount alignment".

**Pull request merged**
