### PR TITLE
Lexer cleanup

### PR DESCRIPTION
**Pull request by dnicolodi**
Some more simplifications in the parser. Some more steps toward porting the lexer to RE/flex.

### CODE REVIEW

**Comment by dnicolodi** [comment]
Rebased. The test failure with Python 3.8 is already there and fixed by #561. I still have no idea about the Bazel build failure.

**Comment by dnicolodi** [comment]
Rebased again. Now only the Bazel build is failing.

**Comment by dnicolodi** [comment]
Thank you for merging. I'll cleanup and submit the RE/flex stuff a soon as possible.

**Comment by blais** [comment]
Sorry for the delay; I've been really busy these days.
No rush!

**Pull request merged**
