### PR TITLE
Implement construction of lexer tokens semantic values in compiled code

### PR DESCRIPTION
**Pull request by dnicolodi**
This builds on top of #498.

### CODE REVIEW

**Comment by dnicolodi** [comment]
Getting the compilation of the new tests right took a few iterations, but it should be good now. I have no idea of how to do the same with Bazel.

**Comment by blais** [comment]
Note: I'll massage a few minor things for consistency. Thank you Daniele,

**Comment by dnicolodi** [comment]
Thanks for reviewing and merging. Drop me a line (here or elsewhere) when you finish with the adjustments so I can rebase the followup patches on top and submit the next PR.

**Comment by blais** [comment]
I'm done

**Pull request merged**
