### PR TITLE
typings: improve; add py.typed marker

### PR DESCRIPTION
**Pull request by yagebu**
- use future import to avoid interpretation of types outside of type
  checking
- some minor fixes in types and/or docstrings as well
- mypy infers some weird stuff for Decimal.as_tuple() - hence some
  ignores for those

### CODE REVIEW

**Comment by trim21** [comment]
should we consider merge https://github.com/beancount/fava/tree/main/stubs/beancount into this repo?

**Comment by blais** [comment]
Yes and no. I think we should add type annotations everywhere.
Last week I did an experiment to do this with LLMs and it ... worked. Amazing.
I then setup aider and aider.el and then I got busy.
I think this could be easy, but I want to check all the diffs.

**Comment by trim21** [comment]
> Yes and no. I think we should add type annotations everywhere. Last week I did an experiment to do this with LLMs and it ... worked. Amazing. I then setup aider and aider.el and then I got busy. I think this could be easy, but I want to check all the diffs.

I cause some misunderstanding, I mean merge pyi type annotation back to source python file, not as seprated pyi type stub.

**Comment by blais** [comment]
Sure, but I feel that having an LLM generate high quality versions is equivalent to me.
Sometimes even better, I've seen it fix errors!

**Pull request merged**
