### PR TITLE
style: enable ruff isort rule

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Comment by blais** [comment]
Is there a way to configure isort so that it doesn't import multiple symbols on the same line?
I've avoided that historically in this codebase.
Not a huge deal to change but if it's possible I'd like it better that way.

**Comment by trim21** [comment]
> Is there a way to configure isort so that it doesn't import multiple symbols on the same line? I've avoided that historically in this codebase. Not a huge deal to change but if it's possible I'd like it better that way.

yes

**Comment by blais** [comment]
Please make the change then, much appreciated.

**Comment by trim21** [comment]
> Please make the change then, much appreciated.

done

**Pull request merged**
